config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contactus' => 'pages#contactus'  

  ActiveAdmin.routes(self)
  devise_for :users
    as :user do
      get "login" => 'devise/sessions#new'
      delete "signout" => 'devise/sessions#destroy'
      get "signup" => 'devise/registrations#new'
    end
    
  get 'feed', to: 'feed#show'

  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end

  resources :tweets do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
    
    def authorized?(action, subject = nil) 
        user && user.admin?
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  
  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 172 }
  
  acts_as_votable
  
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         
  has_many:tweets   
  
  validates :username, presence: true, uniqueness: true, length: {minimum: 5}
  validates :name, presence: true
  
  acts_as_followable
  acts_as_follower
  acts_as_voter
  
end

app/controllers/application_controller.rb
  
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end  

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!
  def show
    @tweetings = Tweet.where(user: current_user.all_following)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  
  def create
      @user = User.find_by(username: params[:username])
      Follow.create(followable: @user, follower: current_user)
      redirect_to user_path(@user.username), notice: "Successfully followed user"
  end
  
  def destroy
      @user = User.find_by(username: params[:username])
      Follow.find_by(followable: @user, follower: current_user).destroy
      redirect_to user_path(@user.username), notice: "Successfully unfollowed user"
  end

  def show
    @user = User.find_by(username: params[:username])
    Follow.follow_count
    Follow.followers_count
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def index
    @followings = Tweet.all
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tail was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tail was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find_by(username: params[:username])
     @tweets = @user.tweets
     @tweetings = Tweet.where(user: current_user.all_following)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  
  def create
     tweet = Tweet.find(params[:id])
     tweet.liked_by current_user
     redirect_to :back, notice: "You have successfully liked a tweet"
  end
  
  def destroy
      tweet = Tweet.find(params[:id])
      tweet.unliked_by current_user
      redirect_to :back , notice: "You have successfully unliked a tweet"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/show.html.erb
<div class="container">
    <p></p>
    <% @tweetings.reverse_each do |tweet, posted| %>   
        <div class="card bg-light" style="width: 18rem;">
            <div class="card-body">
                <!-- for some reason below I can't make a link_to the user :/ -->
                <h5 class="card-title"><%= link_to tweet.user.username, user_path(tweet.user.username) %></h5>
                <p class="card-text"><%= tweet.content %></p>
                <p><%= tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
            </div>
        </div>
        <p></p>
    

    <% end %>

</div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>petSNAP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar navbar-brand https://getbootstrap.com/docs/4.0/components/navbar/-->
    <nav class="navbar navbar-light navbar-toggleable-sm navbar-custom navbar-expand-md" style="background-color:#ffea00;">
      <div class="container">
        <%= link_to "petSNAP", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav mr-auto">
          <!--<li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>-->
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contactus_path, class: "nav-link" %></li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Your homepage", user_path(current_user.username), class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>

          <% else %>
            <li class="nav-item"><%= link_to "Sign up", signup_path, class: "btn btn-info" %></li>
            <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
          <% end %>  
        </ul>
      </div>
    </nav>

    <!--flash messages  -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class:"alert alert-info #{name}")%>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2019 MaeEnterprises</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>petSNAP is a website designed for people to share pictures and stories about their pets. This website will hopefully inspire you to help your furry little friends to do some amazing and funny tricks</a>.</p>
        <p>So why not try 
            <% if user_signed_in? %>
               signing up or logging in 
            <% else %>
                <%= link_to "signing up", signup_path %> or
                <%= link_to "logging in", login_path %>
            <% end %>
            (if you already have an account).
        </p>
        <p>I’m a year 7 and this is a project I've been doing with my dad to learn the programming language Ruby on Rails</p>
    </div>
    <div class="container">
    <%= image_tag("catpicture1.jpg", :size => "800x500", class: "img-fluid")%> <!--   class: "img-responsive center-block"   image creative commons via https://www.flickr.com/photos/jerryliu/15116765570/in/photolist-p2PnK9-fXRSo-dZ8JwZ-oX8Dp7-9FjWdg-aT7akM-ahuXf8-e4LY68-uYQ2H-65fjVh-ajyBYj-kL8Fcc-96GYDJ-d55j3Y-hDVqdM-6iwBTH-pw68qo-deRX6L-deRX8Y-97uBZ7-aqXARD-owVkdM-uYQ9N-atBJxp-qWFs4R-8wjaRr-Ea2e9Y-deRX5d-7EQcep-4SxWCr-9c8DxY-8tkTfR-a9mSXv-miJggD-5w5Goo-eeDEiJ-2bxR29N-cUPhgC-79VHsD-daswEJ-Nx5pV1-deRX7T-2aCm4MT-5tDdFG-jQHaxM-DeyeNT-5EYifD-9Bct2H-9dxDnZ-5zkGTy-->
    </div>
    
    <div class='container'>   
        <% if user_signed_in? %>
           <p></p>  
        <% else %>
            <p></p>
            <%= link_to "Sign up now!", signup_path, class: "btn btn-info btn-lg" %>  
            &nbsp &nbsp &nbsp &nbsp 
            <%= link_to "Or log in", login_path %> 
        <% end %>
    </div>     
</div>

app/views/pages/contactus.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact us</h1>
        <p>We at petSNAP are a friendly bunch so we would really love to hear from you. </p>
        <p>You can get in touch via <a href="mailto:contactpetsnap@gmail.com" >our email </a> or <a href="https://twitter.com/pet__SNAP">Twitter.</a>
        We will reply as soon as possible. Thanks. </p>
    </div>
    <div class="container">
    <%= image_tag("dogpic.jpg", class: "img-fluid")%> <!-- :size => "800x500",  image creative commons via https://www.flickr.com/photos/120866016@N08/22448748385/in/photolist-AcHGMX-Q4yKMR-h1HYth-2buQvJW-5m6zu-2dPKrNX-RFSapy-5tJ18y-24KKseb-SWpxEp-2dPKosi-qGTV-dgybdX-2cHNY85-9a6VSN-e1ctpa-7NmdGx-x9Rnzw-8uLCEK-TjyjCu-27RwMqY-83d4v3-83dbnY-2b4b2aU-23pnKjD-28F3Les-aZdwwk-usEQgq-cGygjh-9ArATa-9ZiFee-gYevJn-oHscv7-vQ7gN-23NDX3L-dhn55-pexaR-PxCdr7-a1ZNpj-RFSceL-cAKgDL-3bgHMT-mkA8gW-pnsFk-zezo1-9chkcQ-6JKi63-21zXMxC-dhnCPz-2eckssT-->
    </div>
    
    <div class='container'>   
        <% if user_signed_in? %>
           <p></p>  
        <% else %>
            <p></p>
            <%= link_to "Sign up now!", signup_path, class: "btn btn-info btn-lg" %>  
            &nbsp &nbsp &nbsp &nbsp 
            <%= link_to "Or log in", login_path %> 
        <% end %>
    </div>     
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome back!</h1>
            <p>petSNAP: Purrrfect fun for you and your furry friends</p>
        </div>
    </div>
      <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Explore</h2>
                <p>See what other petSNAP users are talking about</p>
                <p><%= link_to "View all Tails", tweets_path, class: "btn btn-info" %></p>
            </div>
            <div class="col-md-4">
                 <h2>Share</h2>
                <p>Update us with daily pics and 'tails' about your pets with your family, friends and like minded animal lovers</p>
                <p><%= link_to "New Tail", new_tweet_path, class: "btn btn-info" %></p>
            </div>
            <div class="col-md-4">
               <h2>Home</h2>
                <p> Update your status with your pet's latest hilarious habits and see Tails from the people you follow </p>
                <p><%= link_to "Your Homepage", user_path(current_user.username), class: "btn btn-info" %></p>
            </div>
        </div>
    </div>
    
    
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome to petSNAP!</h1>
            <p>Purrrfect fun for you and your furry friends</p>
            <%= link_to "Learn more »", about_path, class: "btn btn-info btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Explore</h2>
                <p>See what other petSNAP users are talking about</p>
                <p><%= link_to "View all Tails", tweets_path, class: "btn btn-info" %></p>
            </div>
            <div class="col-md-4">
                 <h2>Share</h2>
                <p>Update us with daily pics and 'tails' about your pets with your family, friends and like minded animal lovers</p>
                <p><%= link_to "Log In", login_path, class: "btn btn-secondary" %></p>
            </div>
            <div class="col-md-4">
               <h2>Home</h2>
                <p> Update your status with your pet's latest hilarious habits and see Tails from the people you follow </p>
                <p><%= link_to "Log In", login_path, class: "btn btn-secondary" %></p>
            </div>
        </div>
    </div>
<% end %>

<p></p>
<p></p>
<div class='container'>
    <!--<h2>Tails</h2>
        <!-- @followings.reverse_each do |tweet, posted| %>  --> 
            <!--<div class="card bg-light" style="width: 18rem;">
                <!--<div class="card-body">
                    <!--<p class="card-text"><!-- tweet.content %></p>
                    <!--<p><!-- tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
                <!--</div>
            <!--</div>
            <p></p>
        <!-- end %>
</div>

app/views/tweets/_form.html.erb
<%= form_for(tweet, html: {multipart: true}) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
  
      <ul>
      <% tweet.errors.full_messages.each do |message| %>
         <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control'%>
  </div>
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  
  <%= f.submit 'Submit Tail', class: 'btn btn-info'%>
  
<% end %>

app/views/tweets/edit.html.erb
<div class='container'>
    <p></p>
    <h1>Editing Tail</h1>
    <div class="card bg-light mb-3" style="width: 18rem;">
        <div class="card-body" >
            <center>
            <%= image_tag @tweet.image, class: "img-fluid", 
                src: ' ',
                onerror: "this.style.display='none'"
             %>
            </center>
          
        </div>
    </div>
    <p> </p>
    <%= render 'form', tweet: @tweet %>
    <p></p>
    <p></p>
    <p></p>
    <%= link_to 'Back to Tails', tweets_path %>
    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
    <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %>


    
</div>

app/views/tweets/index.html.erb
<div class='container'>
  <h1>Tails &nbsp  &nbsp  &nbsp &nbsp
    <% if user_signed_in? %>
      <%= link_to "New Tail", new_tweet_path, class: "btn btn-info btn-lg" %>  
      </h1>
    <% end %>
  </h1>
  
    <tbody>
      <% @tweets.reverse_each do |tweet, posted| %>
        <div class="mt-3">
          <div class="card bg-light" style="width: 18rem;">
            <div class="card-body">
              <!-- I can't make the line below link_to tweet.user.username, user_path(tweet.user.username) -->
              <!-- This used to work, but I can't work out what has changed from the earlier commit -->
              <!-- It only works locally with link_to current_user.username, user_path(current_user.username)   which is obviously wrong as it names all the tweets as the current user -->
              <% if user_signed_in? %>
                  <h5 class="card-title"> <%= link_to tweet.user.username, user_path(tweet.user.username) %> </h5>
              <% else %>
                  <h5 class="card-title"> <%= tweet.user.username %> </h5>
              <% end %>
              
              <center>
                <%= image_tag tweet.image, class: "img-fluid", 
                  src: ' ',
                  onerror: "this.style.display='none'"
                %>
              </center>
              
              <p> </p>
              <p class="card-text"><%= tweet.content %></p>
              <p><%= tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
              
                  <p>Likes: <%= tweet.votes_for.up.size %>
                    <% if user_signed_in? %>
                      &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                      <% if current_user.voted_up_on? tweet %>
                        <%= link_to 'Unlike', unvote_tweet_path(tweet), method: :delete %>
                      <% else %>
                        <%= link_to 'Like', vote_tweet_path(tweet), method: :post %>
                      <% end %>
                    <% end %>
                  </p>

                  <% if tweet.user == current_user %>
                  <a href="#" class="card-link"><%= link_to 'Edit', edit_tweet_path(tweet) %></a>      
                  <% end %>
                  <p> </p>
            </div>
          </div>
        </div>
      <% end %>
    </tbody>
    
  <p></p>
  
  <% if user_signed_in? %>
    <%= link_to "New Tail", new_tweet_path, class: "btn btn-info btn-lg" %>  
  <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-info btn-lg" %>  
    &nbsp &nbsp &nbsp &nbsp 
    <%= link_to "Or log in", login_path %> 
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class='container'>
    <p> </p>
    <h1>New Tail</h1>

    <%= render 'form', tweet: @tweet %>
    <p></p>
    <%= link_to 'Back', tweets_path %>
    
</div>
<center>
    <p> </p>
    <p> </p>
    <%= image_tag("jocat.jpg", class: "img-fluid")%> 
    
</center>

app/views/tweets/show.html.erb
<div class='container'>
  
  <p id="notice"><%= notice %></p>
  
  <div class="mt-3">
          <div class="card bg-light mb-3" style="width: 18rem;">
            <div class="card-body" >
              <h5 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h5>
              <center><%= image_tag @tweet.image, class: "img-fluid", 
                src: ' ',
                onerror: "this.style.display='none'"
              %></center>
              <p> </p>
              <p class="card-text"><%= @tweet.content %></p>
              <% if @tweet.user == current_user %>
              <a href="#" class="card-link"><%= link_to 'Edit', edit_tweet_path(@tweet) %></a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link">           </a>
              <a href="#" class="card-link"><%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %></a>
              <% end %>
              <p> </p>
              <p><%= @tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
            </div>
          </div>
        </div>
        
  <div class='container'>
    <!--- <p> likes here -> </p> -->
  </div>

  <div class='container'>
    <p> </p>
    <%= link_to "Back", tweets_path, class: "btn btn-info" %>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
    <p></p>
    <h1> <%= @user.username %> </h1> 
    <p></p>
    
    <% if @user == current_user %>
        <%= link_to "New Tail", new_tweet_path, class: "btn btn-info btn-md" %>  
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <%= link_to 'Back to all Tails', tweets_path %>
        <p></p>
  
    <% else %>
          <% if current_user.following?(@user) %>
              <%= link_to 'Unfollow', unfollow_user_path(@user.username), method: :delete %>
              &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  <%= link_to 'Back to all Tails', tweets_path %>
              <p> </p>
         
          <% else %>
              <%= link_to 'Follow', follow_user_path(@user.username), method: :post, class: "btn btn-info btn-sm" %>
              &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  <%= link_to 'Back to all Tails', tweets_path %>
              <p></p>
          <% end %>
    <% end %>
    
    <p></p>
    <%= image_tag("jocat.jpg", class:"img-fluid", :size => "300x190")%> 
    <p></p>
    
    <% if @user == current_user %>
      <h3>Your Status: &nbsp &nbsp  </h3>
      <p> I have a pet! So I use petSNAP!! It's GREAT!!!!!!!</p>
    <% else %>
       <h3> <%= @user.username %>'s Status:</h3>
       <p> I have a pet! So I use petSNAP!! It's GREAT!!!!!!!</p>
    <% end %>      
      
    <p>
      <% if @user == current_user %>  
          <p>You follow: <%= @user.follow_count %> 
          &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
          Following you: <%= @user.followers_count %>
      <% else %>  
          <p>They follow: <%= @user.follow_count %> 
          &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
          Following them: <%= @user.followers_count %>
          <p></p>
      <% end %> 
    </p>
    
    <% if @user == current_user %>
      <%= link_to "Edit status", "#", class: "btn btn-info btn-sm" %>
    <% end %>  
    
    <% if @user == current_user %>
      <p></p>
      <h3> Tails from people you follow:</h3>
      <p></p>

      <div class="container">
          <% @tweetings.reverse_each do |tweet, posted| %>   
            <div class="card bg-light" style="width: 18rem;">
                <div class="card-body">
                    <!-- for some reason below I can't make a link_to the user :/ -->
                    <h5 class="card-title"><%= link_to tweet.user.username, user_path(tweet.user.username) %></h5>
                    <center><%= image_tag tweet.image, class: "img-fluid", 
                      src: ' ',
                      onerror: "this.style.display='none'"
                    %></center>
                    <p> </p>
                    <p class="card-text"><%= tweet.content %></p>
                    <p><%= tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
                    <p>Likes: <%= tweet.votes_for.up.size %>
                      &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                      <% if user_signed_in? %>
                        <% if current_user.voted_up_on? tweet %>
                          <%= link_to 'Unlike', unvote_tweet_path(tweet), method: :delete %>
                        <% else %>
                          <%= link_to 'Like', vote_tweet_path(tweet), method: :post %>
                        <% end %>
                      <% end %>
                </div>
            </div>
            <p></p>
          <% end %>
      </div>
    
    <% else %>
      <a href="#" class="card-link">           </a>
      <a href="#" class="card-link">           </a>
      <h3> <%= @user.username %>'s Tails </h3>
      <p></p>
      <p></p>
    
      <tbody>
        <% @tweets.reverse_each do |tweet, posted| %>
          <div class="mt-3">
            <div class="card bg-light" style="width: 18rem;">
              <div class="card-body">
                <center><%= image_tag tweet.image, class: "img-fluid", 
                    src: ' ',
                    onerror: "this.style.display='none'"
                %></center>
                <p> </p>
                <p class="card-text"><%= tweet.content %></p>
                <p><%= tweet.created_at.strftime('%H:%M, %e %b %Y')%></p>
                <p>Likes: <%= tweet.votes_for.up.size %>
                  <% if user_signed_in? %>
                      &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
                      <% if current_user.voted_up_on? tweet %>
                        <%= link_to 'Unlike', unvote_tweet_path(tweet), method: :delete %>
                      <% else %>
                        <%= link_to 'Like', vote_tweet_path(tweet), method: :post %>
                      <% end %>
                  <% end %>
                <p> </p>
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    <% end %> 

  <br>
  
  <% if @user == current_user %>
    <%= link_to "New Tail", new_tweet_path, class: "btn btn-info btn-lg" %>  
  <% else %>
    <% if current_user.following?(@user) %>
        <%= link_to 'Back to all Tails', tweets_path %>
        <p> </p>
         
      <% else %>
        <%= link_to 'Follow', follow_user_path(@user.username), method: :post, class: "btn btn-info btn-sm" %>
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  <%= link_to 'Back to all Tails', tweets_path %>
        <p></p>
     <% end %>
  <% end %>

</div>